name: "Claude Quota Scheduler"
description: "Optimize Claude Code quota with automated ghost pings. Never waste a quota refresh again."
author: "Vibe Works"

branding:
  icon: "clock"
  color: "orange"

inputs:
  # Authentication
  oauth_token:
    description: "Claude Code OAuth token"
    required: false
  anthropic_api_key:
    description: "Anthropic API key (alternative to oauth_token)"
    required: false

  # Scheduler config
  account_name:
    description: "Account name for logs/identification"
    required: false
    default: "default"
  timezone:
    description: "IANA timezone (e.g., 'Asia/Shanghai')"
    required: false
    default: "UTC"
  ping_prompt:
    description: "Prompt for ghost ping"
    required: false
    default: "ping"
  model:
    description: "Model to use"
    required: false
    default: "claude-sonnet-4-20250514"

  # Options
  dry_run:
    description: "Log without pinging"
    required: false
    default: "false"
  summary_style:
    description: "Summary style: minimal, detailed, ascii-art"
    required: false
    default: "ascii-art"

  # Cloud providers (pass-through to base-action)
  use_bedrock:
    description: "Use AWS Bedrock"
    required: false
    default: "false"
  use_vertex:
    description: "Use Google Vertex AI"
    required: false
    default: "false"

outputs:
  success:
    description: "Whether ping succeeded"
    value: ${{ steps.result.outputs.success }}
  window_end:
    description: "Quota window end time (ISO 8601)"
    value: ${{ steps.result.outputs.window_end }}
  summary:
    description: "Human-readable summary"
    value: ${{ steps.result.outputs.summary }}

runs:
  using: "composite"
  steps:
    - name: Start
      id: start
      shell: bash
      run: |
        echo "=============================================="
        echo "  Claude Quota Scheduler"
        echo "  Account: ${{ inputs.account_name }}"
        echo "  Timezone: ${{ inputs.timezone }}"
        echo "=============================================="
        echo "start_time=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT

    - name: Dry Run
      if: inputs.dry_run == 'true'
      id: dry_run
      shell: bash
      run: |
        echo "[DRY RUN] Would send: '${{ inputs.ping_prompt }}'"
        echo "conclusion=success" >> $GITHUB_OUTPUT

    - name: Ghost Ping
      if: inputs.dry_run != 'true'
      id: ping
      uses: anthropics/claude-code-action-base@beta
      with:
        prompt: ${{ inputs.ping_prompt }}
        claude_code_oauth_token: ${{ inputs.oauth_token }}
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        use_bedrock: ${{ inputs.use_bedrock }}
        use_vertex: ${{ inputs.use_vertex }}
        claude_args: "--model ${{ inputs.model }} --max-turns 1 --dangerously-skip-permissions"

    - name: Result
      id: result
      if: always()
      shell: bash
      run: |
        ACCOUNT="${{ inputs.account_name }}"
        TZ="${{ inputs.timezone }}"
        STYLE="${{ inputs.summary_style }}"
        DRY="${{ inputs.dry_run }}"

        # Get conclusion from either dry_run or ping step
        if [ "$DRY" = "true" ]; then
          CONCLUSION="${{ steps.dry_run.outputs.conclusion }}"
        else
          CONCLUSION="${{ steps.ping.outputs.conclusion }}"
        fi

        # Calculate window end (5h from now)
        WINDOW_END=$(date -u -d "+5 hours" +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u -v+5H +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || echo "")

        if [ "$CONCLUSION" = "success" ]; then
          SUCCESS="true"
          STATUS="OK"
        else
          SUCCESS="false"
          STATUS="FAILED"
        fi
        [ "$DRY" = "true" ] && STATUS="DRY_RUN"

        echo "success=$SUCCESS" >> $GITHUB_OUTPUT
        echo "window_end=$WINDOW_END" >> $GITHUB_OUTPUT

        # Generate summary
        NOW=$(TZ="$TZ" date "+%Y-%m-%d %H:%M:%S" 2>/dev/null || date "+%Y-%m-%d %H:%M:%S")

        if [ "$STYLE" = "ascii-art" ]; then
          if [ "$SUCCESS" = "true" ]; then
            cat >> $GITHUB_STEP_SUMMARY << 'EOF'
        ```
        ╔════════════════════════════════════════════╗
        ║       QUOTA SCHEDULER - PING RESULT        ║
        ╠════════════════════════════════════════════╣
        EOF
            echo "║  Account: $(printf '%-32s' "$ACCOUNT") ║" >> $GITHUB_STEP_SUMMARY
            echo "║  Status:  ✓ $(printf '%-30s' "$STATUS") ║" >> $GITHUB_STEP_SUMMARY
            echo "║  Time:    $(printf '%-32s' "$NOW") ║" >> $GITHUB_STEP_SUMMARY
            cat >> $GITHUB_STEP_SUMMARY << 'EOF'
        ╠════════════════════════════════════════════╣
        ║       (\__/)                               ║
        ║       (o^.^)  "Quota ready!"               ║
        ║       |>  <>|                              ║
        ╚════════════════════════════════════════════╝
        ```
        EOF
          else
            cat >> $GITHUB_STEP_SUMMARY << 'EOF'
        ```
        ╔════════════════════════════════════════════╗
        ║       QUOTA SCHEDULER - PING RESULT        ║
        ╠════════════════════════════════════════════╣
        EOF
            echo "║  Account: $(printf '%-32s' "$ACCOUNT") ║" >> $GITHUB_STEP_SUMMARY
            echo "║  Status:  ✗ $(printf '%-30s' "$STATUS") ║" >> $GITHUB_STEP_SUMMARY
            cat >> $GITHUB_STEP_SUMMARY << 'EOF'
        ╠════════════════════════════════════════════╣
        ║       (\__/)                               ║
        ║       (T_T)   "Ping failed..."             ║
        ║       |>  <>|                              ║
        ╚════════════════════════════════════════════╝
        ```
        EOF
          fi
        else
          echo "## Quota Scheduler: $ACCOUNT" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** $STATUS" >> $GITHUB_STEP_SUMMARY
          echo "**Time:** $NOW ($TZ)" >> $GITHUB_STEP_SUMMARY
          [ "$SUCCESS" = "true" ] && echo "**Window End:** $WINDOW_END" >> $GITHUB_STEP_SUMMARY
        fi

        # Set summary output
        echo "summary=[$STATUS] $ACCOUNT @ $NOW" >> $GITHUB_OUTPUT
