name: "Claude Quota Scheduler"
description: "Optimize Claude Code quota with automated ghost pings. Never waste a quota refresh again."
author: "Vibe Works"

branding:
  icon: "clock"
  color: "orange"

inputs:
  oauth_token:
    description: "Claude Code OAuth token"
    required: false
  anthropic_api_key:
    description: "Anthropic API key (alternative to oauth_token)"
    required: false
  account_name:
    description: "Account name for logs"
    required: false
    default: "default"
  timezone:
    description: "IANA timezone (e.g., 'Asia/Shanghai')"
    required: false
    default: "UTC"
  ping_prompt:
    description: "Prompt for ghost ping (be creative!)"
    required: false
    default: "draw a tiny ascii art of yourself waking up from a nap, yawning. keep it under 5 lines."
  model:
    description: "Model to use (sonnet, haiku, opus)"
    required: false
    default: "sonnet"
  dry_run:
    description: "Log without pinging"
    required: false
    default: "false"
  summary_style:
    description: "Summary style: minimal, detailed, ascii-art"
    required: false
    default: "ascii-art"

outputs:
  success:
    description: "Whether ping succeeded"
    value: ${{ steps.result.outputs.success }}
  window_end:
    description: "Quota window end time (ISO 8601)"
    value: ${{ steps.result.outputs.window_end }}
  summary:
    description: "Human-readable summary"
    value: ${{ steps.result.outputs.summary }}
  claude_response:
    description: "What claude said/drew"
    value: ${{ steps.ping.outputs.response }}
  bark_message:
    description: "Claude-generated notification message"
    value: ${{ steps.ping.outputs.bark_message }}

runs:
  using: "composite"
  steps:
    - name: Start
      shell: bash
      run: |
        echo "=============================================="
        echo "  Claude Quota Scheduler"
        echo "  Account: ${{ inputs.account_name }}"
        echo "  Timezone: ${{ inputs.timezone }}"
        echo "=============================================="

    - name: Install Claude CLI
      if: inputs.dry_run != 'true'
      shell: bash
      run: |
        echo "Installing Claude Code CLI..."
        for attempt in 1 2 3; do
          if curl -fsSL https://claude.ai/install.sh | bash; then
            echo "$HOME/.local/bin" >> "$GITHUB_PATH"
            export PATH="$HOME/.local/bin:$PATH"
            echo "Claude CLI installed: $(claude --version 2>/dev/null || echo 'installed')"
            break
          fi
          [ $attempt -eq 3 ] && { echo "::error::Failed to install Claude CLI"; exit 1; }
          sleep 5
        done

    - name: Ghost Ping
      id: ping
      shell: bash
      run: |
        ACCOUNT="${{ inputs.account_name }}"
        DRY="${{ inputs.dry_run }}"
        PROMPT="${{ inputs.ping_prompt }}"
        MODEL="${{ inputs.model }}"

        if [ "$DRY" = "true" ]; then
          echo "[DRY RUN] Would send: '$PROMPT' to model $MODEL"
          echo "conclusion=success" >> $GITHUB_OUTPUT
          echo "bark_message=dry run - no actual ping" >> $GITHUB_OUTPUT
          exit 0
        fi

        echo "Sending ghost ping..."
        export PATH="$HOME/.local/bin:$PATH"

        # append bark message request to prompt
        FULL_PROMPT="$PROMPT

also write a funny one-liner (max 50 chars) for a push notification about this. put it on its own line starting with BARK:"

        # capture output
        RESPONSE=$(timeout 120 claude -p "$FULL_PROMPT" \
          --model "$MODEL" \
          --max-turns 1 \
          --dangerously-skip-permissions \
          2>&1) && EXIT_CODE=0 || EXIT_CODE=$?

        echo "$RESPONSE"

        if [ $EXIT_CODE -eq 0 ]; then
          echo "conclusion=success" >> $GITHUB_OUTPUT

          # extract bark message (line starting with BARK:)
          BARK_MSG=$(echo "$RESPONSE" | grep -i "^BARK:" | head -1 | sed 's/^BARK:[[:space:]]*//' | cut -c1-50)
          if [ -z "$BARK_MSG" ]; then
            BARK_MSG="claude woke up and did a thing"
          fi

          # escape for github output
          echo "bark_message=$BARK_MSG" >> $GITHUB_OUTPUT

          # save full response (escape newlines)
          {
            echo 'response<<EOF'
            echo "$RESPONSE"
            echo 'EOF'
          } >> $GITHUB_OUTPUT

          echo "Ping successful!"
        else
          echo "conclusion=failure" >> $GITHUB_OUTPUT
          echo "bark_message=claude refused to wake up" >> $GITHUB_OUTPUT
          echo "::warning::Ping failed or timed out"
        fi
      env:
        CLAUDE_CODE_OAUTH_TOKEN: ${{ inputs.oauth_token }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}

    - name: Result
      id: result
      if: always()
      shell: bash
      run: |
        ACCOUNT="${{ inputs.account_name }}"
        TZ="${{ inputs.timezone }}"
        STYLE="${{ inputs.summary_style }}"
        CONCLUSION="${{ steps.ping.outputs.conclusion }}"

        # Calculate window end (5h from now)
        WINDOW_END=$(date -u -d "+5 hours" +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u -v+5H +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || echo "N/A")

        if [ "$CONCLUSION" = "success" ]; then
          SUCCESS="true"
          STATUS="OK"
        else
          SUCCESS="false"
          STATUS="FAILED"
        fi
        [ "${{ inputs.dry_run }}" = "true" ] && STATUS="DRY_RUN"

        echo "success=$SUCCESS" >> $GITHUB_OUTPUT
        echo "window_end=$WINDOW_END" >> $GITHUB_OUTPUT

        NOW=$(TZ="$TZ" date "+%Y-%m-%d %H:%M:%S" 2>/dev/null || date "+%Y-%m-%d %H:%M:%S")

        if [ "$STYLE" = "ascii-art" ]; then
          if [ "$SUCCESS" = "true" ]; then
            cat >> $GITHUB_STEP_SUMMARY << EOF
        \`\`\`
        ╔════════════════════════════════════════════╗
        ║       QUOTA SCHEDULER - PING RESULT        ║
        ╠════════════════════════════════════════════╣
        ║  Account: $(printf '%-32s' "$ACCOUNT")║
        ║  Status:  ✓ $(printf '%-30s' "$STATUS")║
        ║  Time:    $(printf '%-32s' "$NOW")║
        ╠════════════════════════════════════════════╣
        ║       (\\__/)                               ║
        ║       (o^.^)  "Quota ready!"               ║
        ║       |>  <>|                              ║
        ╚════════════════════════════════════════════╝
        \`\`\`
        EOF
          else
            cat >> $GITHUB_STEP_SUMMARY << EOF
        \`\`\`
        ╔════════════════════════════════════════════╗
        ║       QUOTA SCHEDULER - PING RESULT        ║
        ╠════════════════════════════════════════════╣
        ║  Account: $(printf '%-32s' "$ACCOUNT")║
        ║  Status:  ✗ $(printf '%-30s' "$STATUS")║
        ╠════════════════════════════════════════════╣
        ║       (\\__/)                               ║
        ║       (T_T)   "Ping failed..."             ║
        ║       |>  <>|                              ║
        ╚════════════════════════════════════════════╝
        \`\`\`
        EOF
          fi
        else
          echo "## Quota Scheduler: $ACCOUNT" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** $STATUS" >> $GITHUB_STEP_SUMMARY
          echo "**Time:** $NOW ($TZ)" >> $GITHUB_STEP_SUMMARY
          [ "$SUCCESS" = "true" ] && echo "**Window End:** $WINDOW_END" >> $GITHUB_STEP_SUMMARY
        fi

        echo "summary=[$STATUS] $ACCOUNT @ $NOW" >> $GITHUB_OUTPUT
