name: "Claude Quota Scheduler"
description: "Optimize your Claude Code quota with automated ghost pings. Never waste a quota refresh again."
author: "Vibe Works"

branding:
  icon: "clock"
  color: "orange"

inputs:
  oauth_token:
    description: "Claude Code OAuth token (primary account)"
    required: false

  oauth_tokens:
    description: "JSON object mapping account names to OAuth tokens for multi-account setup"
    required: false

  config_file:
    description: "Path to YAML config file (relative to repo root)"
    required: false
    default: ""

  timezone:
    description: "IANA timezone name (e.g., 'America/New_York', 'Asia/Shanghai')"
    required: false
    default: "UTC"

  ping_prompt:
    description: "Minimal prompt to send for ghost ping"
    required: false
    default: "ping"

  model:
    description: "Claude model to use for ping"
    required: false
    default: "claude-sonnet-4-20250514"

  accounts:
    description: "Comma-separated list of account names to ping (for matrix builds)"
    required: false
    default: "default"

  account_name:
    description: "Single account name (for matrix job naming)"
    required: false
    default: ""

  dry_run:
    description: "Log actions without actually pinging"
    required: false
    default: "false"

  debug:
    description: "Enable debug logging"
    required: false
    default: "false"

  summary_style:
    description: "GitHub summary style: minimal, detailed, or ascii-art"
    required: false
    default: "detailed"

  notification_webhook:
    description: "Webhook URL for notifications (optional)"
    required: false

  notification_on_success:
    description: "Send notification on success"
    required: false
    default: "false"

  notification_on_failure:
    description: "Send notification on failure"
    required: false
    default: "true"

  claude_version:
    description: "Claude CLI version to install"
    required: false
    default: "latest"

  path_to_claude_executable:
    description: "Path to existing Claude executable (skip install)"
    required: false
    default: ""

outputs:
  success:
    description: "Whether all pings succeeded"
    value: ${{ steps.scheduler.outputs.success }}

  accounts_pinged:
    description: "JSON array of successfully pinged accounts"
    value: ${{ steps.scheduler.outputs.accounts_pinged }}

  accounts_failed:
    description: "JSON array of failed accounts"
    value: ${{ steps.scheduler.outputs.accounts_failed }}

  next_windows:
    description: "JSON object mapping accounts to their next quota window end times"
    value: ${{ steps.scheduler.outputs.next_windows }}

  summary:
    description: "Human-readable summary of the run"
    value: ${{ steps.scheduler.outputs.summary }}

runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: "1.2.11"

    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        bun install --frozen-lockfile 2>/dev/null || bun install

    - name: Install Claude CLI
      if: inputs.path_to_claude_executable == '' && inputs.dry_run != 'true'
      shell: bash
      run: |
        CLAUDE_VERSION="${{ inputs.claude_version }}"
        echo "Installing Claude CLI${CLAUDE_VERSION:+ v$CLAUDE_VERSION}..."

        for attempt in 1 2 3; do
          echo "Attempt $attempt..."
          if curl -fsSL https://claude.ai/install.sh | bash -s -- ${CLAUDE_VERSION}; then
            echo "$HOME/.local/bin" >> "$GITHUB_PATH"
            echo "Claude CLI installed successfully"
            break
          fi
          if [ $attempt -eq 3 ]; then
            echo "::error::Failed to install Claude CLI after 3 attempts"
            exit 1
          fi
          sleep 5
        done

    - name: Setup custom Claude path
      if: inputs.path_to_claude_executable != ''
      shell: bash
      run: |
        CLAUDE_DIR=$(dirname "${{ inputs.path_to_claude_executable }}")
        echo "$CLAUDE_DIR" >> "$GITHUB_PATH"
        echo "Using custom Claude executable: ${{ inputs.path_to_claude_executable }}"

    - name: Run Quota Scheduler
      id: scheduler
      shell: bash
      run: |
        bun run ${{ github.action_path }}/src/index.ts
      env:
        INPUT_OAUTH_TOKEN: ${{ inputs.oauth_token }}
        INPUT_OAUTH_TOKENS: ${{ inputs.oauth_tokens }}
        INPUT_CONFIG_FILE: ${{ inputs.config_file }}
        INPUT_TIMEZONE: ${{ inputs.timezone }}
        INPUT_PING_PROMPT: ${{ inputs.ping_prompt }}
        INPUT_MODEL: ${{ inputs.model }}
        INPUT_ACCOUNTS: ${{ inputs.accounts }}
        INPUT_ACCOUNT_NAME: ${{ inputs.account_name }}
        INPUT_DRY_RUN: ${{ inputs.dry_run }}
        INPUT_DEBUG: ${{ inputs.debug }}
        INPUT_SUMMARY_STYLE: ${{ inputs.summary_style }}
        INPUT_NOTIFICATION_WEBHOOK: ${{ inputs.notification_webhook }}
        INPUT_NOTIFICATION_ON_SUCCESS: ${{ inputs.notification_on_success }}
        INPUT_NOTIFICATION_ON_FAILURE: ${{ inputs.notification_on_failure }}
        INPUT_PATH_TO_CLAUDE_EXECUTABLE: ${{ inputs.path_to_claude_executable }}
        GITHUB_STEP_SUMMARY: ${{ github.step_summary }}

    - name: Post Summary
      if: always()
      shell: bash
      run: |
        if [ -f "${{ runner.temp }}/quota-scheduler-summary.md" ]; then
          cat "${{ runner.temp }}/quota-scheduler-summary.md" >> $GITHUB_STEP_SUMMARY
        fi
